controller_manager:
  ros__parameters:
    update_rate: 50

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
  joints:
    - finger_width

finger_width_controller:
  type: position_controllers/JointPositionController
  joints:
    - finger_width
